//
// Created by camel on 22. 9. 21.
//

#ifndef CAMEL_CONSOLE_GAMEPADDESCRIPTION_HPP
#define CAMEL_CONSOLE_GAMEPADDESCRIPTION_HPP

enum COMMAND
{
    CMD_NO_ACT,
    CMD_START,
    CMD_RECOVERY,
    CMD_RESET,
    CMD_HOME_UP,
    CMD_HOME_DOWN,
    CMD_TROT_OVERLAP,
    CMD_TROT_SLOW,
    CMD_TROT_FAST,
    CMD_TROT_STOP,
    CMD_E_STOP
};

enum FSM
{
    FSM_INITIAL,
    FSM_EMERGENCY_STOP,
    FSM_READY,
    FSM_ISOLATION,
    FSM_CONST_STAND,
    FSM_STAND,
    FSM_TROT_SLOW,
    FSM_TROT_FAST,
    FSM_OVERLAP_TROT_FAST
};

#endif //CAMEL_CONSOLE_GAMEPADDESCRIPTION_HPP
