//
// Created by camel on 22. 9. 21.
//

#ifndef RAISIM_ROBOTDESCRIPTION_H
#define RAISIM_ROBOTDESCRIPTION_H


enum LEG_INDEX
{
    FL_IDX = 0,
    FR_IDX,
    HL_IDX,
    HR_IDX
};

enum CAN_STATE
{
    CAN_NO_ACT,
    CAN_INIT,
    CAN_MOTOR_ON,
    CAN_MOTOR_OFF,
    CAN_SET_TORQUE,
    CAN_READ_ERROR,
    CAN_READ_ENCODER
};

enum GAIT_TYPE
{
    STAND = 0,
    TROT_SLOW,
    TROT_FAST,
    OVERLAP_TROT_FAST
};

enum GAIT_COMMAND
{
    DESIRED_GAIT_STAND,
    DESIRED_GAIT_TROT_SLOW,
    DESIRED_GAIT_TROT_FAST,
    DESIRED_GAIT_OVERLAP_TROT_FAST
};

enum FSM
{
    FSM_INITIAL,
    FSM_READY,
    FSM_STAND_UP,
    FSM_SIT_DOWN,
    FSM_STAND,
    FSM_TROT_STOP,
    FSM_TROT_SLOW,
    FSM_TROT_FAST,
    FSM_OVERLAP_TROT_FAST,
    FSM_EMERGENCY_STOP,
    FSM_RESTART,
    FSM_WHEEL2FOOT_CHANGE,
    FSM_FOOT2WHEEL_CHANGE,
    FSM_WHEEL_STAND,
    FSM_WHEEL_MOVE
};

#endif //RAISIM_ROBOTDESCRIPTION_H
